# Generated by Django 5.0.12 on 2025-02-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Telefone'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_jid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='JID do WhatsApp'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome no WhatsApp'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_profile_pic',
            field=models.URLField(blank=True, null=True, verbose_name='Foto de Perfil do WhatsApp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Usuário'),
        ),
    ]
