# Generated by Django 5.0.12 on 2025-02-17 20:29

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number_user_whatsapp_jid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR', unique=True, verbose_name='Número de Telefone'),
        ),
    ]
