# Generated by Django 5.0.12 on 2025-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp_jid',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='JID do WhatsApp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome no WhatsApp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_profile_pic',
            field=models.URLField(blank=True, verbose_name='Foto de Perfil do WhatsApp'),
        ),
    ]
