# Generated by Django 5.0.12 on 2025-02-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='qrcode_url',
            field=models.URLField(blank=True, help_text='URL do QR Code para ativação da instância', null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='token',
            field=models.CharField(blank=True, help_text='Token da instância gerado pela Evolution API', max_length=255, null=True),
        ),
    ]
