# Generated by Django 5.0.12 on 2025-02-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsappinstance_integration_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappinstance',
            name='api_key',
            field=models.CharField(blank=True, help_text='Chave de API gerada automaticamente', max_length=255, null=True),
        ),
    ]
