# Generated by Django 5.0.12 on 2025-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_alter_whatsappinstance_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappinstance',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Chave de API gerada automaticamente', max_length=255),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='qrcode_url',
            field=models.URLField(blank=True, default='', help_text='URL do QR Code para ativação da instância'),
        ),
        migrations.AlterField(
            model_name='whatsappinstance',
            name='token',
            field=models.CharField(blank=True, default='', help_text='Token da instância gerado pela API', max_length=255),
        ),
    ]
