# Generated by Django 5.0.12 on 2025-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_alter_whatsappinstance_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappinstance',
            name='qrcode_url',
            field=models.TextField(blank=True, default='', help_text='URL do QR Code para ativação da instância'),
        ),
    ]
